### PR TITLE
Help on Enum typed argument will list options by their Enum constant nam...

### PR DESCRIPTION
**Pull request by vruano**
...e rather than what is returned by toString.

Resolves issue #371.

### CODE REVIEW

**Comment by lbergelson** [comment]
@vruano I made comments [here](https://github.com/broadinstitute/hellbender/commit/2161c3aca51ab1d11b14ddfb8d4e4827670bb53f) before you opened this pull request.    I think it's the same code that you moved into this pull request.  If those don't work for you for some reason, let me know and I'll re-comment on this pull request.

**Comment by vruano** [comment]
About ClpEnum, I wonder whether you can use an annotation on the constants to provide additional information instead of implementing an interface. 

I think is a more neat solution... With ClpEnum you are forcing the Enum constructor to collect the documentation into a field for this to work.

**Comment by vruano** [comment]
@lbergelson please review.
Test pass locally and they should not fail on Travis.

**Comment by lbergelson** [comment]
:+1:

**Pull request merged**
