### PR TITLE
updating dependencies

### PR DESCRIPTION
**Pull request by lbergelson**
updating dataflow and htsjdk to newest versions
adding gradle versions plugin to help with identifying dependencies that need updates

This broke one of our spark related tests so I've excluded it for now.  See #581.  It should be reeneabled when https://github.com/cloudera/spark-dataflow/issues/49 is complete.

### CODE REVIEW

**Comment by lbergelson** [comment]
@davidadamsphd Please review ( assuming tests pass...)

**Comment by tomwhite** [comment]
@lbergelson I've released spark-dataflow 0.2.0 with an update for the latest dataflow version. If you incorporate https://github.com/tomwhite/hellbender/commit/7b4caaac36515b8da0dd9fb197c7cf4cd351ec49 into this PR all the Spark tests should pass.

**Comment by lbergelson** [comment]
@tomwhite Wow, that was fast.  We didn't even manage to merge this before you got it fixed.  Thanks.

**Comment by davidadamsphd** [comment]
+1. Looks good to merge.

**Pull request merged**
