### PR TITLE
use diamond types <>

### PR DESCRIPTION
**Pull request by akiezun**

### CODE REVIEW

**Comment by akiezun** [comment]
@lbergelson please review

**Comment by lbergelson** [comment]
What's the trick to do this automatically?

**Comment by akiezun** [comment]
will tell you once we merge it

**Comment by lbergelson** [comment]
:+1:

**Comment by akiezun** [comment]
In IntelliJ, use Analyze | Run Inspection by name ... | Explicit type can be replaced by <> 
Then right-click the top level in the inspection window and apply the fix.

**Pull request merged**
