### PR TITLE
Bump htsjdk version to 1.132

### PR DESCRIPTION
**Pull request by droazen**
This fixes a data loss bug with `VCFHeader`

### CODE REVIEW

**Comment by droazen** [comment]
For @lbergelson to review

**Comment by lbergelson** [comment]
What's the deal with that test changing exceptions?

**Comment by droazen** [comment]
htsjdk now throws an exception in certain cases in which it didn't previously throw anything, so in certain cases in this test case we the new exception from htsjdk, and in other cases htsjdk doesn't throw but hellbender does and we get a different exception. Common ancestor is `RuntimeException`

**Comment by lbergelson** [comment]
I think it's wrong to relax the error type.  The error is in the test setup code, not the line that's meant to throw.

Should we remove that test case now instead since it seems htsdjk protects against it?

**Comment by lbergelson** [comment]
Although I suppose protecting against us writing an invalid file isn't the same as protecting against reading one...

**Comment by droazen** [comment]
No, since htsjdk doesn't protect us against every case exercised in this test. It's still a valid and meaningful test, and shouldn't be deleted.

**Comment by lbergelson** [comment]
Then we need to refactor the test to write the file itself, since HTJDK won't.

**Comment by droazen** [comment]
That would not be a valid test, since it wouldn't be testing the way the code actually handles invalid intervals. All we want to know is that we throw when we encounter an invalid interval.

Did I mention that this very simple change is urgently needed by many branches?

**Comment by droazen** [comment]
@lbergelson Addressed issues with that test -- please re-review

**Comment by lbergelson** [comment]
:+1:

**Pull request merged**
