### PR TITLE
Ak apply vqsr on tranches branch

### PR DESCRIPTION
**Pull request by akiezun**
@droazen please review

### CODE REVIEW

**Comment by akiezun** [comment]
hmm.

**Comment by akiezun** [comment]
@droazen @lbergelson i can't reproduce the error that travis is reporting on the pull req: https://travis-ci.org/broadinstitute/hellbender/builds/58990321
Here's what I run:
```
git clone --depth=50 git://github.com/broadinstitute/hellbender.git broadinstitute/hellbender
cd broadinstitute/hellbender/
git fetch origin +refs/pull/383/merge:
git checkout -qf FETCH_HEAD
gradle assemble
```
and my tests all pass.

**Comment by akiezun** [comment]
1 missing line in the list above. Add it at the end:
```
gradle check
```

**Comment by akiezun** [comment]
assigning to @droazen. Not sure if the errors we're seeing are real or a github/travis artifact.

**Comment by akiezun** [comment]
removing milestone. vqsr is not on the critical path.

**Comment by droazen** [comment]
Am un-assigning this, as it's not clear that we want to merge this at this time. Feel free to re-assign if you'd like to see this merged.

**Comment by akiezun** [comment]
closing for now

**Pull request closed without merging**
