### PR TITLE
minor

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
Adding documentation as a way to test the process.

### CODE REVIEW

**Comment by akiezun** [comment]
:+1: merge at will

**Comment by jean-philippe-martin** [comment]
Done, thank you!

**Comment by akiezun** [comment]
@jean-philippe-martin  after a merge, delete the branch

**Comment by akiezun** [comment]
Welcome to Hellbender!

**Comment by akiezun** [comment]
@jean-philippe-martin can you delete the branch?

**Comment by jean-philippe-martin** [comment]
sure thing, I deleted it now. Sorry for not doing it earlier!

**Pull request merged**
