### PR TITLE
Add a dbsnp 138 vcf snippet with variants from the first 65 mbp of chromosome 1

### PR DESCRIPTION
**Pull request by droazen**
Requires a "git lfs pull" to access. File size is ~230 MB.

### CODE REVIEW

**Comment by droazen** [comment]
For @jean-philippe-martin to review, please.

**Comment by droazen** [comment]
@tomwhite You should switch to using this vcf in your bqsr tests, as well (assuming you stick with that CEUTrio.HiSeq.WGS.b37.ch1.1m-65m.NA12878.bam bam)

**Comment by lbergelson** [comment]
I verify that this looks like a vcf file and index.

**Comment by jean-philippe-martin** [comment]
I didn't see this on Friday, but it looks good to me.

**Pull request merged**
