### PR TITLE
Fixed IOUtils.createTempFile() so that it deletes files on exit as promised in its docs

### PR DESCRIPTION
**Pull request by droazen**

### CODE REVIEW

**Comment by droazen** [comment]
Somehow the final version of `IOUtils.createTempFile()` got clobbered during the review of https://github.com/broadinstitute/hellbender/pull/682/ so that it wasn't deleting on exit. This restores the lost `deleteOnExit()` call.

**Comment by droazen** [comment]
For @lbergelson to review please

**Comment by lbergelson** [comment]
Ack, that was a mistake.

**Comment by lbergelson** [comment]
:+1:

**Pull request merged**
