### PR TITLE
ported pairhmms

### PR DESCRIPTION
**Pull request by akiezun**
PairHMMs ported - for now, including the JNI ones (may delete them in the future)
but not including FastLoglessPairHMM for now (it may only be used in the graph likelihood engine and that engine may not be used)

as per internal discussions, all PairHMMs will be public.

@vruano please review and advise on keeping or deleting FastLoglessPairHMM and the graph based likelihood engine.

### CODE REVIEW

**Comment by droazen** [comment]
I would like to see the native implementations removed from this pull request. Porting them now introduces lots of new sources of error at too early a stage in hellbender development.

**Comment by vruano** [comment]
IMO I would only port LoglessPairHMM for a first iteration ... base on the premature optimization approach it should be Log10PairHMM as the former is an optimization of the later but I believe it makes a huge difference. 

I second @droazen, I think JNI ones should be added later to get the performance back.

About the GraphBased approach... I never got it to fly as it could as I was pulled to do other stuff. I think it should not be ported for now anyway.

**Comment by vruano** [comment]
@akiezun could you please collapse the commits; when I start commenting changes in one I wonder whether it has been addressed in a later commit.

**Comment by akiezun** [comment]
@vruano done
btw, this code is pretty much unchanged fomr the gatk3 version. Very small modifications due to using SAMRecord etc.

**Comment by vruano** [comment]
@akiezun what kind of review do you want me to do then? just point out the small changes like finals, {} NPEs...), right?

**Comment by akiezun** [comment]
Yes, plus point out any classes that should not be ported etc, like you did
with the other classes.

On Thursday, June 4, 2015, Valentin Ruano Rubio <notifications@github.com>
wrote:

> @akiezun <https://github.com/akiezun> what kind of review do you want me
> to do then? just point out the small changes like finals, {} NPEs...),
> right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/hellbender/pull/543#issuecomment-108718766>
> .
>


-- 
Sent from Gmail Mobile

**Comment by vruano** [comment]
@akiezun 

I don't have anything against porting the classes that are ported except ```MostLikelyAllele``` which is only reference by testing code (or perhaps I'm missing something?) It might need to be ported eventually but not at this time.

Coverage is poor for PairHMM instances and this seems due to the fact that there are no unit test for PairHMM's computeLikelihoods and it was covered just by integration test back in GATK3. Can you add some unit-testing here? That would require to include an implementor of LikelihoodMatrix also in the pull request.

Apart from that please correct code formatting issues (finals, missing {} and so forth).

**Comment by akiezun** [comment]
back to @vruano

**Comment by vruano** [comment]
Done with the review. Back to @akiezun

**Comment by akiezun** [comment]
done with comments. back to @vruano

**Comment by vruano** [comment]
Looks good, just consider my only comment; you decide.

Back to @akiezun

**Pull request merged**
