### PR TITLE
Change CompareSAMs to obey validation stringency; re-enable two integ…

### PR DESCRIPTION
**Pull request by cmnbroad**
…ration tests. The fix for the original bug (CompareSAMs not obeying stringency) is a one line fix in CompareSAMs. The two BQSR integration tests referenced in the issue use a different code path and required a different fix (assuming that relaxing the stringency is the right thing to do in those cases).

I also added a new CompareSAMs integration test and changed the CompareSAMs tool to return  result of the comparison.

### CODE REVIEW

**Comment by akiezun** [comment]
this is for https://github.com/broadinstitute/hellbender/issues/419

**Comment by akiezun** [comment]
@droazen or @lbergelson  can you review it? If not, I'll have a look on Wednesday

**Comment by droazen** [comment]
Before we review, would you mind rebasing this onto the latest master (in case substantial changes are needed)? Thanks!

**Comment by cmnbroad** [comment]
Sure.

**Comment by droazen** [comment]
looks good :+1:

**Pull request merged**
