### PR TITLE
Serialize auth onto pipeline

### LINKED ISSUE #864: BQSR_Dataflow doesn't work with client-secrets.json
it only works with API_KEY. Ultimately the problem is that RefAPISource calls GenomicsOptions.Methods.getGenomicsAuth at the worker. That's too late: that function creates an Offline auth by reading the client-secrets file. The solution is to create an OfflineAuth object at the client and then pass that to RefAPISource somehow.

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
Fixes #864.

### CODE REVIEW

**Comment by jean-philippe-martin** [comment]
Fails on the cloud test, at testBQSRCloud[0].assertEqualTextFiles(IntegrationTestSpec.java:185) (?)

**Comment by lbergelson** [comment]
Looks like a real test failure. 

screen shot 2015-08-28 at 11 42 32 am


[the actual result](https://files.zenhub.io/55e081ab12ce86823ac9a2a0)

[what was expected](https://files.zenhub.io/55e081ab12ce86823ac9a2a1)

**Comment by lbergelson** [comment]
I triggered a manual rebuild to try to see if it's some sort of non-deterministic sharding issue.

**Comment by jean-philippe-martin** [comment]
I'm going to put this aside for a bit and focus on the other work since we can use the API_KEY as a workaround.

**Comment by jean-philippe-martin** [comment]
It looks like there's a data race somewhere in BQSR, as the test fails when we're using multiple cores but passes when we're using a single one (or even multiple single-core machines, as I've tested separately).

Meanwhile I can merge this in once someone LGTM's it.

**Comment by jean-philippe-martin** [comment]
Rebasing ahead of time, so Louis gets to review the final version of the code.

**Comment by davidadamsphd** [comment]
I looked over it. It looks good (LGTM).
My only request is a comment saying something to the effect of why the credentials can be sent around (apparently not machine specific?)

**Comment by lbergelson** [comment]
@jp . I'm on vacation this week, so I'd have someone else review if you want it in soon.

**Pull request merged**
