### PR TITLE
Assembly engine for the haplotype caller

### PR DESCRIPTION
**Pull request by akiezun**
This pull requests includes includes assembly graph code and surrounding utility classes + tests. I added a whole bunch of tests and tweaked a whole bunch of code (some more, some much less). 

@vruano please review

### CODE REVIEW

**Comment by eitanbanks** [comment]
Woo hoo!

**Comment by vruano** [comment]
Done. I have skipped the Test classes as quality is not important on those IMO.
Back to @akiezun

**Comment by akiezun** [comment]
back to @vruano - i split into 2 commits (first one is just braces everywhere)

**Comment by vruano** [comment]
Done, minor changes.
Good work.

I can see that in many places arguments are not check for nulls, you should try to spot as many as you can and fix them. 

Also when you choose to postpone modification to do later after this merge, you need to add a corresponding issue in github so that it will be picked up later.

After all this you can rebase and merge.

**Pull request merged**
