### PR TITLE
Add option to broadcast reference data to reads in Spark

### LINKED ISSUE #855: Looking into broadcasting reference to all workers for native Spark Reads pipeline
Look into broadcasting the reference to all of the workers. This would make AddContextDataToReadSpark and the BQSR code simpler and may have better performance than our current code.

### PR DESCRIPTION
**Pull request by laserson**
Fixes #855.

Not finished yet.

### CODE REVIEW

**Comment by laserson** [comment]
One technical issue: I am subclassing a Scala class.  Hope this doesn't cause wonkiness.

**Comment by tomwhite** [comment]
We should be able to move to just using JoinReadsWithVariants, and avoid using AddContextDataToReadSpark (which uses JoinReadsWithRefBases). I did something like that in these two commits: https://github.com/broadinstitute/hellbender/commit/eb82408af03b2ddfdad947689fc9d22b2b18e82e, https://github.com/broadinstitute/hellbender/commit/864040a780c93d85dcfa73fa385187a128e069e9.

Also, using a 2bit representation would be great as it would use less memory. If it's a lot more work we can use the existing ReferenceBases implementation to start with.

**Comment by droazen** [comment]
We want to continue to go through `AddContextDataToReadSpark` at the top level, if possible, because we want that to be our standard interface for joining reads with all kinds of overlapping data. We can certainly add a mode in which it assumes that the reference is broadcast and just joins reads with variants.

**Comment by tomwhite** [comment]
I added some comments to individual commits since the overall change is so large.

Have you managed to run this with a real .2bit file yet? You could also add a test like the one here: https://github.com/broadinstitute/hellbender/commit/503dd1858e82c634a784db64426d702523a8643f (computation runs successfully, but tests fails due to output difference).

**Comment by laserson** [comment]
Oh, yeah, sorry,  rebased this onto the bqsr branch.  That's why it's so huge

**Comment by laserson** [comment]
I was trying to run it with a 2bit file but the code was breaking before it even got to the reference join.

**Comment by laserson** [comment]
Closing in favor of #919

**Pull request closed without merging**
