### PR TITLE
test for CollectWgsMetrics

### PR DESCRIPTION
**Pull request by akiezun**
addresses #708

### CODE REVIEW

**Comment by akiezun** [comment]
@lbergelson  can you have a look why the LFS files are working on one of the test configs and not the other? The test is CollectWgsMetrics and uses the big bam file + fasta

**Comment by lbergelson** [comment]
The large files aren't yet working in travis.  Known issue, we're working on it..

**Comment by lbergelson** [comment]
@akiezun git-lfs should now be working.  Rebase this branch on master and try again.

**Comment by akiezun** [comment]
simply rebasing does not do it. back to @lbergelson for advice

**Comment by akiezun** [comment]
nevermind, it works now. merging

**Comment by akiezun** [comment]
ok, tests pass. back to @lbergelson for review

**Comment by lbergelson** [comment]
:+1:   One test is better than none test.

**Pull request merged**
